name: Create Plugin Zip

on:
  push:
    branches:
      - Scheduling--Feature--Update # Run only on our target branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create plugin directory
        run: |
          mkdir -p /tmp/improve-seo

      - name: Copy plugin files
        run: |
          rsync -av --exclude=".git" --exclude=".github" --exclude=".gitignore" --exclude="node_modules" . /tmp/improve-seo/

      - name: Create ZIP file
        run: |
          cd /tmp
          zip -r improve-seo.zip improve-seo

      - name: Upload zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: improve-seo
          path: /tmp/improve-seo.zip
          retention-days: 90

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/improve-seo.zip
          asset_name: improve-seo.zip
          asset_content_type: application/zip
